#
BIN_ALL = KEYSERVER SERVER CLIENT
GEN_C1KP = C1K_xdr.c C1K_clnt.c C1K_svc.c C1K.h
GEN_C2SP = C2S_xdr.c C2S_clnt.c C2S_svc.c C2S.h
LIB = -lnsl
CFLAGS = -I.. -O 
CC = gcc -DDEBUG

all:            $(GEN_C1KP) $(GEN_C2SP) $(BIN_ALL)

$(GEN_C1KP):         C1K.x
		rpcgen -N C1K.x
		
$(GEN_C2SP):         C2S.x
		rpcgen -N C2S.x

KEYSERVER:         C1K_svc.o C1K_xdr.o KP_proc.o
		$(CC) -o $@ KP_proc.c C1K_svc.o C1K_xdr.o $(LIB)
		
SERVER:         C2S_svc.o C2S_xdr.o SP_proc.o
		$(CC) -o $@ SP_proc.c C2S_svc.o C2S_xdr.o $(LIB)
		
CLIENT:         C1K_clnt.c C1K_xdr.o C2S_clnt.c C2S_xdr.o CP.o
		$(CC) -o $@ CP.c C1K_clnt.c C1K_xdr.o C2S_clnt.c C2S_xdr.o $(LIB)
	
CP.o:       CP.c C1K.h C2S.h

KP_proc.o:         KP_proc.c C1K.h

SP_proc.o:         SP_proc.c C2S.h

clean:
		rm -f $(GEN_C1KP) $(GEN_C2SP) *.o $(BIN_ALL)

#